name: pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
env:
  IMAGE_NAME: ayi-githubactions
  DB_CONNECTION: ${{ secrets.DB_CONNECTION }}

jobs:
  
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    # steps to perform in job
    steps:
      - name: build and push image
        uses: actions/checkout@v3
      - run: |
          sudo apt install gettext
          envsubst < config.ini > config.ini
          cat config.ini
          docker build -t $IMAGE_NAME:latest .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker tag $IMAGE_NAME ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest
          
                 
  deploy-to-cluster:
    name: deploy to cluster
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
    - name: deploy to cluster
      uses: actions/checkout@v3
    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply -f cronjob.yaml
